Research UI marker style
CAMPUS-NYCU/smart-campus pull request #31
Opened 2023-10-27 06:11 UTC by hsinlun99

# Description

# Changes

# Notes
Keep "Unknown" status for "" selectedKeys (in AddReportDrawerContent and EditReportDrawerContent)

# Checklist

- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [X] Any changes to strings have been published to our translation tool
- [X] I conducted basic QA to assure all features are working
- [X] I requested code review from other team members

# Resolved Issues

2023-10-27 13:32 UTC, y-c-wang requested changes
Please address the comments, and remember to put your GitHub id in the front of branch name (i.e., `<your github id>/<the feature>`). Also, please attach snapshots for any UI changes.

2023-10-27 13:32 UTC, y-c-wang commented on firebase/storage.rules
> +      allow write: if request.auth != null;
Already fixed in #30.

```suggestion
      allow read, write: if request.auth != null;
```

2023-10-27 13:32 UTC, y-c-wang commented on src/constants/model/poi/index.ts
The result would be like this. Just to remind that you may be addressing #10 with another PR.

![image](https://github.com/CAMPUS-NYCU/smart-campus/assets/98584755/731a1570-73f4-4d8d-a41b-d0f6437164b0)

2023-10-27 13:32 UTC, y-c-wang commented on src/utils/googleMaps/markers/poi/icons.ts
> +export const getIcon = (poiData: PoiData) => {
```suggestion
export const getIcon = (status: PoiStatus): google.maps.Icon => {
```

2023-10-27 13:32 UTC, y-c-wang commented on src/utils/googleMaps/markers/poi/icons.ts
> +    default:
```suggestion
    case "unknown":
    default:
```

2023-10-27 13:32 UTC, y-c-wang commented on src/constants/model/poi/index.ts
> +  usage: "usage",
Good practice to alphabetize them:)

2023-10-27 13:32 UTC, y-c-wang commented on src/constants/model/poi/index.ts
>    unknown: "unknown",
Please reorder to put `unknown` to be the last one

2023-10-29 03:20 UTC, closed without merging

2023-10-29 03:20 UTC, hsinlun99 commented
Thank you!
I think this PR is part of https://github.com/CAMPUS-NYCU/smart-campus/issues/10 
I will close this one and address these commits in another branch with the correct naming style