[Research]UI: cluster drawer updates to meet research requirement.
CAMPUS-NYCU/smart-campus pull request #38
Opened 2023-11-09 08:46 UTC by hsinlun99

# Description
1. Cluster Drawer UI change to meet the research requirement
2. Fix several typos in message keys

# Changes
1. cluster drawer
![image](https://github.com/CAMPUS-NYCU/smart-campus/assets/43398440/90e28ee8-cb65-4df8-b1b1-49590fa79097)
2. poi drawer (still needs to be updated)
![image](https://github.com/CAMPUS-NYCU/smart-campus/assets/43398440/d5fe5c37-f791-45e1-a858-bd3f0bc1143e)
![image](https://github.com/CAMPUS-NYCU/smart-campus/assets/43398440/705e8bff-ce6f-41b8-813f-f6aa110331bc)

# Notes
- highlight the corresponding poi marker is still unfinished.
- the "編輯" button is still unfinished.
![image](https://github.com/CAMPUS-NYCU/smart-campus/assets/43398440/08dfeb42-6d93-4b77-877b-d405acb66117)

# Checklist

- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] Any changes to strings have been published to our translation tool
- [X] I conducted basic QA to assure all features are working
- [X] I requested code review from other team members

# Resolved Issues

2023-11-09 12:55 UTC, y-c-wang requested changes
## PR Scope

Please make the next PR smaller and focus on **one** feature, e.g.
- change cluster drawer to contain the POIs within it
  - in this PR no additional changes need to be done, it is ok to use just a block with a string to denote the POI
- add chip of floor for POIs in cluster drawer
- add image placeholder for POIs in cluster drawer
- ...


## List changes in this PR

Please list all of the changes in this PR

2023-11-09 14:19 UTC, hsinlun99 commented
## Changes
### changes for new feature
- set the drawer height as 50vh for poi and cluster to meet research requirement
- update information displayed in cluster (e.g. delete cluster position, add [building name]現有回報資訊)
- add a list to contain pois in cluster
  - list `poi.data.target.category`, `poi.data.target.serial`, `poi.data.target.floor`, `poi.data.status.type`, `poi.data.status.value` to meet research requirement
  - list `poi.data.updateAt` or `poi.data.createdAt` (depends on whether the poi is updated) to meet the research requirement
  - add chip for floor, status type, and status value
  - add "編輯" button for research requirement (function is still unfinished)
  - add image place holder for research requirement (function is still unfinished)

### fix prior typos
- nonfunctional key error: correct bad to broken
- notCrowded key error: correct noSpaces to notCrowded
- badCleanliness key error: correct goodCleanliness to badCleanliness

2023-11-10 14:38 UTC, linyc0817 commented on src/components/Drawer/ClusterDrawer/index.tsx
> +        <div className="container flex flex-row justify-around space-x-0.5 py-0 h-[calc((50vh-100px)/4)]">
maybe using "h-fit" will be better. Let the height increase with the content.

2023-11-10 16:25 UTC, linyc0817 commented on src/components/Drawer/ClusterDrawer/index.tsx
> +            <div className="flex flex-wrap flex-row space-x-1">
add text-align left to allow text move to the left when wrapping

2023-11-10 16:29 UTC, linyc0817 commented on src/locale/en-us/drawer.json
>          "description": "Description: {{description}}",
Did we still have description in our clusterDrawer content ?

2023-11-10 16:36 UTC, linyc0817 requested changes
Some style suggestion

2023-11-14 05:08 UTC, hsinlun99 commented on src/components/Drawer/ClusterDrawer/index.tsx
> +            <div className="flex flex-wrap flex-row space-x-1">
If you mean the space before "無障礙停車區1" in this picture, it cannot be solved by adding text-align.
I fixed it in another way. You may check it again to see if it's satisfying :) 
![image](https://github.com/CAMPUS-NYCU/smart-campus/assets/43398440/639327e2-ec64-4420-ab30-f8552756d7bb)

2023-11-14 06:19 UTC, linyc0817 commented on src/components/Drawer/ClusterDrawer/index.tsx
> +            <div className="flex flex-wrap flex-row space-x-1">
我的意思是 "空間/無障礙停車區" 或是 "無障礙停車區1" 這兩欄，如果內容太長導致換行，目前寫法會是置中，但應該要向左看齊。

2023-11-14 09:14 UTC, linyc0817 approved these changes
LGTM

2023-11-14 13:10 UTC, merged