[Research] make the highlighted poi and the yellow flag (when creating a report) centered at the map rather than screen.
CAMPUS-NYCU/smart-campus pull request #69
Opened 2023-12-07 09:20 UTC by hsinlun99

**NEED MERGE https://github.com/CAMPUS-NYCU/smart-campus/pull/66 FIRST**
# Description
- highlighted poi
![image](https://github.com/CAMPUS-NYCU/smart-campus/assets/43398440/69cda040-51d1-49f4-aeb4-11e96c0b06b8)
- yellow flag
![image](https://github.com/CAMPUS-NYCU/smart-campus/assets/43398440/80c516a5-0ad7-4370-9286-e2d1bb0c1fc0)

# Changes

# Notes

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] Any changes to strings have been published to our translation tool
- [ ] I conducted basic QA to assure all features are working
- [ ] I requested code review from other team members

# Resolved Issues
https://github.com/CAMPUS-NYCU/smart-campus/issues/68

2023-12-09 16:31 UTC, linyc0817 requested changes
Well done, only some format need change!

2023-12-09 16:31 UTC, linyc0817 commented on src/components/Drawer/AddReportDrawer/index.tsx
>    const handleDrawerConfirm = () => {
```suggestion
  };
  
  const handleDrawerConfirm = () => {
```

Add a space here.

2023-12-09 16:31 UTC, linyc0817 commented on src/components/Drawer/AddReportDrawer/index.tsx
> +      latitude: north - (north - south) / 4,
```suggestion
      latitude: south + (north - south) * 0.75,
```
Will this be better to understand? Is no just ignore it !

2023-12-10 05:26 UTC, hsinlun99 commented on src/components/Drawer/AddReportDrawer/index.tsx
> +      latitude: north - (north - south) / 4,
我覺得...都行？
不然就改成你那樣好了哈哈哈

2023-12-10 05:43 UTC, merged